### ISSUE TITLE
Add puml as supported file suffix

### ISSUE THREAD

**Issue by forkedjensh** [aklt/plantuml-syntax#49]
Please add puml as a supported file suffix in your plugin as it is our most beloved file suffix in plantuml (to be honest in general).

Pull request to come...

**Comment by aklt** [comment]
Thanks for this, I will add it, but am unable to at the moment.  I hope in the new year ;-)

**Comment by forkedjensh** [comment]
Support for .puml endings was already implemented in a2a20b5052b00ae5d109709f3926d5b13b03359f

**Comment by aklt** [comment]
Heh, you are right!
