### ISSUE TITLE
buffer path is cached

### ISSUE THREAD

**Issue by ambihelical** [aklt/plantuml-syntax#5]
To reproduce, open one file, run `:make`.  Then open another file in another buffer. when `:make` is used, it processes the first file.   This is because `expand("%")` is stored in a static var which caches it the first time the plugin is run. 

My .vimrc workaround:
autocmd Filetype plantuml let &l:makeprg=g:plantuml_executable_script." ".fnameescape(expand("%"))

**Comment by aklt** [comment]
Thanks for the issue @ambihelical, it should be fixed now.
