### ISSUE TITLE
Issue on multiline notes

### ISSUE THREAD

**Issue by nbossard** [aklt/plantuml-syntax#51]
Hello, 
Thanks for this great plugin.
I face an error ofcoloring when I use multiline notes without ":" . e.g. : 

@startuml
state iywe
note left of iywe
        not detected
end note
@enduml

what happens is that the "end note" is not taken into account, and the following text is displayed as part of the note.
if I change it to following it is ok  for your plugin... but KO for plantuml jar

@startuml
state iywe
note left of iywe : 
        not detected
end note
@enduml

**Comment by aklt** [comment]
You are right, there is a problem.  There should probably be a single line note and a multiple line note.
Thanks for the bug report.

**Comment by aklt** [comment]
This seems to be fixed
