### ISSUE TITLE
Vim script page is outdated

### ISSUE THREAD

**Issue by Z0t** [aklt/plantuml-syntax#52]
http://www.vim.org/scripts/script.php?script_id=3538 shows in the main section

0.1 | 2011-04-03 | 6.0

And links to https://vim.sourceforge.io/scripts/download_script.php?src_id=15365

Can you update the link, or the text to this repo in the body?

**Comment by aklt** [comment]
Hello @Z0t , Ihave just updated the page on www.vim.org, thanks for the heads up.
