### ISSUE TITLE
wrong highlighting after multiple line note

### ISSUE THREAD

**Issue by anschnapp** [aklt/plantuml-syntax#54]
i have an highlighting issue after a using inside a class diagram
```
note bottom
    some multiple
    line notes here
note end
```
it seems like all text after this block is also highlighted as a comment in this case. the highlighting for class and attributes etc.. don't work after the multiple line note.

**Comment by hokorobi** [comment]
Should not it be "end note", not "note end" ?

**Comment by aklt** [comment]
If you change the last line to end note it works, but there is a problem with highlighting notes correctly,
see #51
