### ISSUE TITLE
need add @startmindmap .etc support

### ISSUE THREAD

**Issue by zhuyeqing5828** [aklt/plantuml-syntax#67]
Dear aklt :
  The plantuml.vim need update for support MindMap. I saw the plantuml.jar has supported but vim plugin is not supposed.

**Comment by aklt** [comment]
Thanks for letting me know, I would like to have a look at implementing that.

**Comment by aklt** [comment]
Hi @zhuyeqing5828 , just FYI I added a start to this in this commit which highlights 
mindmap like constructs, let me know if you have any comments :-)

https://github.com/aklt/plantuml-syntax/commit/9995b99e5de4431cc3a6fe09e7027cad77ed8ba7#diff-bd0db7d5b132f9ca94a952efa05c5ef1R129

**Comment by zhuyeqing5828** [comment]
Hi @aklt ,The highLight show had solved .But it still have issue like 
> Error detected while processing function slumlord#updatePreview[15]..<SNR>44_mungeDiagramInTmpFile[2]..<SNR>44_convertNonAsciiSupportedSyntax:
The test file source is 
`
@startmindmap
* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
`
May be we should do more work to solve It.

**Comment by aklt** [comment]
Hi @zhuyeqing5828 you are right the syntax highlight of the mindmap
needs some work, I hope to be able to address it.

But the error you show looks to have to do with [slumlord](https://github.com/scrooloose/vim-slumlord)
have you tried asking them?

**Comment by aklt** [comment]
I just ran this without errors from slumlord, so I will close.
