### ISSUE TITLE
Incorrect keyword arrow highlighting

### ISSUE THREAD

**Issue by hokorobi** [aklt/plantuml-syntax#68]
NG, `-up->`
It seems to be caused by the highlight related to mindmap.

https://github.com/aklt/plantuml-syntax-test/blob/master/reference_04-07-1.uml

![image](https://user-images.githubusercontent.com/99910/61196923-d070a480-a70c-11e9-81f6-050dfff1aea8.png)

**Comment by aklt** [comment]
You are right, I should have tested a little better, thanks!

**Comment by aklt** [comment]
And thanks for the pull requests, good to have these things fixed :-)

**Comment by hokorobi** [comment]
Thank you for merging.
I haven't gotten around to this issue yet.

**Comment by aklt** [comment]
I am happy that you like to contribute 👍 

There are quite a few bugs in this highlighting that could be
fixed, but currently I do not have the possibility to use PlantUML
as much as I would like to.  It is a good tool.

Are you using PlantUML a lot?

**Comment by hokorobi** [comment]
PlantUML is a great tool, so I want to use it, but I don't use it much, just for occasional document creation.
