### ISSUE TITLE
Single quote in component name highlighting

### ISSUE THREAD

**Issue by cprn** [aklt/plantuml-syntax#79]
I *think* this is a bug but I don't know enough about syntax files to be sure.

```uml
[Payer's Bank Module] <<Internal Container>> as module
```

The single quote is treated as start of the comment even though it's in the brackets, i.e. name of the component:

![image](https://user-images.githubusercontent.com/6132708/66836284-5ba64400-ef61-11e9-9c07-60e428bbe8e2.png)

**Comment by aklt** [comment]
This is a bug that should for sure, thanks for reporting.
