### ISSUE TITLE
installation help

### ISSUE THREAD

**Issue by joaomcteixeira** [aklt/plantuml-syntax#81]
Hi,

I am not able to get syntax highlight. I must say I am relatively new to vim.
I have sourced all your plugin `*.vim` files. Still, when I open a plantuml file syntax does not show.

I notice that my vim is not being able to read any object type in the plantuml file.

[here is my vim config](https://github.com/joaomcteixeira/jmct-tools/blob/master/.vimrc) (plug in source at the bottom)

If you can help me on this I would appreciate.

Thank you!

**Comment by aklt** [comment]
Hello,

I would think that
```viml
set nocompatible
syntax on
filetype plugin indent on
```
would be required in `.vimrc`

**Comment by gilbertguoze** [comment]
i have this situation either, and i have the 3 lines above in the .vimrc,  but i can't have my .puml file syntax highlight

**Comment by aklt** [comment]
Hope you got it working
